export const SET_PRODUCTS = "SET_PRODUCTS";
export const SELECTED_PRODUCTS = "SELECTED_PRODUCTS";
export const REMOVE_SELECTED_PRODUCTS = "REMOVE_SELECTED_PRODUCTS";
export const USER_ACCOUNT = "USER_ACCOUNT";
export const ADD_TO_WISHLISHT = "ADD_TO_WISHLISHT";
export const ADD_TO_FAV = "ADD_TO_FAV";
export const ADD_TO_CART = "ADD_TO_CART";
